suppressMessages(library("CellTagR"))
suppressMessages(library("Seurat"))
x = readRDS("data/out/anika/anika.RDS")
pbmc = readRDS("data/out/anika/anika_reduction.RDS")
subset = readRDS("data/out/anika/anika_subset_reduction.RDS")
filtered_bc =rownames(x@jaccard.mtx)suppressMessages(library("Seurat"))
x = readRDS("data/out/anika/anika.RDS")
pbmc = readRDS("data/out/anika/anika_reduction.RDS")
subset = readRDS("data/out/anika/anika_subset_reduction.RDS")
filtered_bc =rownames(x@jaccard.mtx)
Idents(pbmc) = "Without quality CellTag"

x = readRDS("data/out/anika/anika.RDS")
pbmc = readRDS("data/out/anika/anika_reduction.RDS")
subset = readRDS("data/out/anika/anika_subset_reduction.RDS")
filtered_bc =rownames(x@jaccard.mtx)
Idents(pbmc) = "Without quality CellTag"
cluster9_bc = x@clone.composition$v1$cell.barcode[x@clone.composition$v1$clone.id == 9]
cluster13_bc = x@clone.composition$v1$cell.barcode[x@clone.composition$v1$clone.id == 13]
Idents(pbmc) = "Without quality CellTag"
pbmc = SetIdent(object = pbmc, cells = cluster9_bc, value = "clone9")
pbmc = SetIdent(object = pbmc, cells = cluster13_bc, value = "clone13")
cluster5.markers <- FindMarkers(pbmc, ident.1 = "clone9", ident.2 = "clone13", min.pct = 0.25)
cluster5.markers
cluster5.markershead(cluster5.markers, n = 5)
head(cluster5.markers, n = 5)
cluster5.markers <- FindMarkers(pbmc, ident.1 = "clone9", ident.2 = "clone13", min.pct = 0.25, logfc.threshold = 0.25)
head(cluster5.markers, n = 5)
cluster5.markers <- FindMarkers(pbmc, ident.1 = "clone9", ident.2 = "clone13", min.pct = 0.25, logfc.threshold = 0.25, only.pos = TRUE)
head(cluster5.markers, n = 5)
cluster5.markers <- FindMarkers(pbmc, ident.1 = "clone13", ident.2 = "clone9", min.pct = 0.25, logfc.threshold = 0.25)
head(cluster5.markers, n = 5)
c9_13__bc = append(cluster9_bc, cluster13_bc)
c9_13 = subset(pbmc, cells = c9_13)
c9_13__bc = append(cluster9_bc, cluster13_bc)
c9_13 = subset(pbmc, cells = c9_13__bc)
pbmc = c9_13
pbmc <- NormalizeData(pbmc)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc), npcs = 26)
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
pbmc <- FindClusters(pbmc, resolution = 1.5)
pbmc <- FindClusters(pbmc, resolution = 1)
length(Indents(pbmc) == 0)
length(Idents(pbmc) == 0)
length(Idents(pbmc) == 1)
Idents(pbmc)
pdf("9_13_clustered.pdf")
pbmc <- RunUMAP(pbmc, dims = 1:10)
DimPlot(pbmc, reduction = "umap")
dev.off()
c9_13__bc = append(cluster9_bc, cluster13_bc)
c9_13 = subset(pbmc, cells = cluster9_bc)
pbmc = c9_13
pbmc <- NormalizeData(pbmc)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc), npcs = 26)
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 1)
pbmc <- FindClusters(pbmc, resolution = 1.2)
pbmc <- FindClusters(pbmc, resolution = 1.1)
pbmc <- FindClusters(pbmc, resolution = 1.05)
pbmc <- RunUMAP(pbmc, dims = 1:10)
pbmc <- FindNeighbors(pbmc, dims = 1:10, n_neighbors=3)
pbmc <- FindClusters(pbmc, resolution = 1.05)
pbmc <- RunUMAP(pbmc, dims = 1:10)
pbmc <- RunUMAP(pbmc, dims = 1:5)
pbmc <- RunUMAP(pbmc, dims = 1:5, verbose=F)
pbmc <- RunTSNE(pbmc)
pbmc <- RunTSNE(pbmc, dims=1:10)
pbmc <- RunTSNE(pbmc, dims=1:5)
pbmc <- RunTSNE(pbmc, dims=1:3)
pbmc <- RunTSNE(pbmc, dims=1:2)
pbmc <- RunTSNE(pbmc, dims=1)
pbmc <- RunTSNE(pbmc, dims=0)
pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
pbmc.markers %>%
    group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)
pbmc.markers
savehistory(file = "some_clustering.R")
