---
title: "Report on the clones"
author: "Markus Heidrich"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_chunk$set(echo = TRUE, fig.width = 12, fig.height = 12)
```

## Report
Show example run of data from Anika.

## Setup

### Load Libraries

libraries required to run this report.

```{r load-libraries}

### Bioconductor and CRAN libraries used
library(knitr)
library(ggplot2)
suppressMessages(library("CellTagR"))
suppressMessages(library("Seurat"))
suppressMessages(library("optparse"))

pbmc = readRDS("data/out/anika/anika_subset_reduction.RDS")
pbmc
DimPlot(pbmc, reduction = "umap")

pbmc.markers <- FindAllMarkers(pbmc, min.pct = 0.25, logfc.threshold = 0.25)
pbmc.markers %>%
   group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)


x = readRDS("data/out/anika/anika.RDS")
table(x@clone.composition$v1$clone.id)

cluster9_bc = x@clone.composition$v1$cell.barcode[x@clone.composition$v1$clone.id == 9]
length(cluster9_bc)

cluster13_bc = x@clone.composition$v1$cell.barcode[x@clone.composition$v1$clone.id == 13]
  
Idents(pbmc) = "Not interested"
pbmc = SetIdent(object = pbmc, cells = cluster13_bc, value = "cluster13")
pbmc = SetIdent(object = pbmc, cells = cluster9_bc, value = "cluster9")
Idents(pbmc)
pbmc.markers %>%
    group_by(cluster) %>%
    slice_max(n = 5, order_by = avg_log2FC)
    
cluster2.markers <- FindMarkers(pbmc, ident.1 = "cluster9", min.pct = 0.25)
head(cluster2.markers, n = 5)
cluster2.markers <- FindMarkers(pbmc, ident.1 = "cluster13", min.pct = 0.25)
head(cluster2.markers, n = 5)
cluster2.markers <- FindMarkers(pbmc, ident.1 = "cluster9",indent.2 = "cluster13", min.pct = 0.25)
head(cluster2.markers, n = 5)
cluster2.markers <- FindMarkers(pbmc, ident.1 = "cluster9",indent.2 = "cluster13", min.pct = 0.25, logfc.threshold = 0.25)
head(cluster2.markers, n = 5)
cluster2.markers <- FindMarkers(pbmc, ident.1 = "cluster13",indent.2 = "cluster9", min.pct = 0.25, logfc.threshold = 0.25)
head(cluster2.markers, n = 5)
```